### ISSUE TITLE
Not able to do horizontal scroll of selected values

### ISSUE THREAD

**Issue by codoffer** [oi-narendra/multiselect-dropdown#101]
We are not able to scroll horizontally during option (item) selection. Please help.

**Comment by ErsinMandaci** [comment]
What is the solution to the problem?

**Comment by oi-narendra** [comment]
Check [Beta](https://pub.dev/packages/multi_dropdown/versions/3.0.0-beta.1) version.

**Comment by oi-narendra** [comment]
Migrate to the latest version [v3.0.0](https://pub.dev/packages/multi_dropdown).
