### ISSUE TITLE
Not be able to remove input extra padding

### ISSUE THREAD

**Issue by Paroca72** [oi-narendra/multiselect-dropdown#102]
Hello,

I'm not able to remove the input extra padding (vertical). 
In picture you can see the problem

![image](https://github.com/oi-narendra/multiselect-dropdown/assets/8638803/16a5f8b3-7a81-4f0d-ac21-62f0a8c971c7)

Here my code but it seem the padding to zero is not enough:
```
    return MultiSelectDropDown<String>(
      padding: EdgeInsets.zero,
      ...
    );
```

Usually for do that on the default DropDownButton, if I recall good, was enough to set isDense to true.
But here I cannot find such property.

Thanks for your support
Sam

**Comment by oi-narendra** [comment]
Check [Beta](https://pub.dev/packages/multi_dropdown/versions/3.0.0-beta.1) version.

**Comment by oi-narendra** [comment]
Migrate to the latest version [v3.0.0](https://pub.dev/packages/multi_dropdown).
