### ISSUE TITLE
Cant change Selected chip border color

### ISSUE THREAD

**Issue by rohanudhwani-blinkx** [oi-narendra/multiselect-dropdown#103]
`Widget _buildFilterButton(String filterName, String filterType, int index,
      String orientation, List<dynamic> filterOptions) {
    final bool isMobile = MediaQuery.of(context).size.width < 600;

    if (filterType == 'text') {
      return _buildTextInputFilter(filterName);
    }

    final MultiSelectController _controller = MultiSelectController();
    Timer? _hideDropdownTimer;
    double totalSubfilterHeight = filterOptions.length * 40.0;
    return MouseRegion(
      onHover: (event) {
        if (orientation == "horizontal") {
          _controller.showDropdown();
        }
      },
      child: Container(
        width: 150,
        height: 43,
        child: MultiSelectDropDown(
          borderRadius: 25,
          borderColor: Colors.grey,
          borderWidth: 0.8,
          hintColor: Theme.of(context).colorScheme.primary,
          fieldBackgroundColor: Theme.of(context).colorScheme.secondary,
          selectedOptionBackgroundColor: Color(0xFF52BDE2),
          optionTextStyle: TextStyle(
            color: Theme.of(context).colorScheme.primary,
            fontSize: isMobile ? 14 : 14,
          ),
          controller: _controller,
          onOptionSelected: (List<ValueItem> selectedOptions) {
            if (selectedOptions.isNotEmpty) {
              List<String> selectedLabels =
                  selectedOptions.map((item) => item.label).toList();
              bool isAllSelected = selectedLabels.contains("ALL");
              if (isAllSelected) {
                // If "ALL" is selected, store it as the only option in the list
                selectedFilters[filterName] = ['ALL'];
              } else {
                // Store the selected options' labels as a list
                selectedFilters[filterName] = selectedLabels;
              }
              widget.onGoPressed(selectedFilters);
            }
          },
          hint: filterName,
          options: filterOptions.map<ValueItem>((subFilter) {
            final item = subFilter as String;
            return ValueItem(label: item, value: filterOptions.indexOf(item));
          }).toList(),
          selectionType: SelectionType.multi,
          chipConfig: const ChipConfig(
            backgroundColor: Color(0xFF60C2AC),
            // wrapType: WrapType.wrap,
          ),
          dropdownHeight: totalSubfilterHeight,
          selectedOptionIcon: const Icon(Icons.check_circle),
        ),
      ),
    );
  }`

![image_2024-07-04_123248327](https://github.com/oi-narendra/multiselect-dropdown/assets/170502129/943c9840-eea8-4aaa-9ab5-99af18b5a4c9)

**Comment by savioalwd** [comment]
Same issue here when this package used, chip background color changes, but the border cant be set to zero and a black color appears

**Comment by oi-narendra** [comment]
Added in [Beta](https://pub.dev/packages/multi_dropdown/versions/3.0.0-beta.1) version.

**Comment by oi-narendra** [comment]
Please migrate to the latest version [v3.0.0](https://pub.dev/packages/multi_dropdown).
