### ISSUE TITLE
How to update options?

### ISSUE THREAD

**Issue by davidcheungo123** [oi-narendra/multiselect-dropdown#104]
I tried to add an item in options based on user's input, however seems like it cannot be updated, what should I do for resolving this issue? Thanks

**Comment by AlaJaber97** [comment]
any update about this issue?
setState(){} not update the option

**Comment by davidcheungo123** [comment]
> any update about this issue? setState(){} not update the option

I resolved the issue, you need to _controller.setOptions for the purpose

**Comment by Paroca72** [comment]
Hello,

I have the same issue but I cannot use the controller.. 
I need to redraw the control every time but it drawn correct only the first time.
I think the problem is that missing the didUpdateWidget implementation inside the control.

Thanks

**Comment by oi-narendra** [comment]
Please check out beta version [Beta](https://pub.dev/packages/multi_dropdown/versions/3.0.0-beta.1).

**Comment by oi-narendra** [comment]
Please migrate to the latest version [v3.0.0](https://pub.dev/packages/multi_dropdown)
