### ISSUE TITLE
Disable whole control is missing

### ISSUE THREAD

**Issue by Paroca72** [oi-narendra/multiselect-dropdown#106]
Hi,

It's seems not possible to disable the control.
I think is something important when use the control inside a form.

Thanks

**Comment by oi-narendra** [comment]
Added in [Beta](https://pub.dev/packages/multi_dropdown/versions/3.0.0-beta.1) version.

The Dropdown now supports Form.

**Comment by oi-narendra** [comment]
[v3.0.0](https://pub.dev/packages/multi_dropdown) now supports this. Please migrate to the latest version.
