### ISSUE TITLE
DEV InputDecoration Widget instead of Icon

### ISSUE THREAD

**Issue by duarm** [oi-narendra/multiselect-dropdown#109]
I'm using the dev version. The new FieldDecoration `prefixIcon` field wants an `Icon?`. Flutter's InputDecoration, and in general, usually asks for a `Widget?`. Can the prefixIcon/suffixIcon fields have a `Widget` type, to be more in line with flutter official APIs?

**Comment by oi-narendra** [comment]
Added in [Beta](https://pub.dev/packages/multi_dropdown/versions/3.0.0-beta.1) version.

**Comment by oi-narendra** [comment]
[v3.0.0](https://pub.dev/packages/multi_dropdown) now supports this.
