### ISSUE TITLE
[Feature] Select all text replacement

### ISSUE THREAD

**Issue by shinriyo** [oi-narendra/multiselect-dropdown#111]
`Select all` is English.
So, I want to replacement option

**Comment by oi-narendra** [comment]
Added in [Beta](https://pub.dev/packages/multi_dropdown/versions/3.0.0-beta.1) version.
use the `hintText` property inside `fieldDecoration`.

**Comment by oi-narendra** [comment]
[v3.0.0](https://pub.dev/packages/multi_dropdown) now supports this.
