### ISSUE TITLE
The Android Bar back button closes the page instead dispose the OverlayEntry

### ISSUE THREAD

**Issue by DevTekoa** [oi-narendra/multiselect-dropdown#113]
I can't find a solution to this problem. My page behind the control is closing when I tap the Android back button.

![Screenshot_20240731_101900 1](https://github.com/user-attachments/assets/39eeb54f-2860-446b-88ce-31a15bc177fd)

**Comment by oi-narendra** [comment]
Added in [Beta](https://pub.dev/packages/multi_dropdown/versions/3.0.0-beta.1) Version.

use `closeOnBackButton` property to use this.

**Comment by oi-narendra** [comment]
[v3.0.0](https://pub.dev/packages/multi_dropdown) now supports this.
