### ISSUE TITLE
[IMPROVEMENT] Expose the on search change method

### ISSUE THREAD

**Issue by alesalv** [oi-narendra/multiselect-dropdown#117]
I would like to be able to be notified when the user is typing the search, but I couldn't find a way, as anything related to the search is private.

So I was thinking something as basic as:
```
MultiDropdown.future(
  onSearchChange: _onSearchChange,
);
```

**Comment by oi-narendra** [comment]
So, the use case would be to implement a custom search ??

**Comment by alesalv** [comment]
My use case is a little bit more complex than that :)
When the user opens the drop down menu, it's populated with 10 random items, but while she types for searching, I should make more calls to the server, and for each refined search the server would return me more refined items, sometimes even more than the initial 10.
As I see it, it's like remote searching instead of local searching. Does this makes sense?
So my idea for this improvement would be to rebuild the menu every time I need to make a new call. I didn't have the time yet to test if this could work, but on the other hand I see exposing the on search change could be beneficial to others anyhow

**Comment by alesalv** [comment]
Opened a [PR](https://github.com/oi-narendra/multiselect-dropdown/pull/119) for this
