### ISSUE TITLE
multi_dropdown 3.0.0 in list view

### ISSUE THREAD

**Issue by ARASHz4** [oi-narendra/multiselect-dropdown#118]
Hi I have some widgets in a ListView and when i scroll down and Dropdown gone out of view and when i come back top of ListView all items in Dropdown disappeared and gave me some errors

i set items with controller

`flutter: Error: Router operation requested with a context that does not include a Router.
flutter: The context used to retrieve the Router must be that of a widget that is a descendant of a Router widget.
======== Exception caught by foundation library ====================================================
The following assertion was thrown while dispatching notifications for MultiSelectController<ServiceUser>:
'package:flutter/src/widgets/overlay.dart': Failed assertion: line 1550 pos 14: '_zOrderIndex != null': is not true.

When the exception was thrown, this was the stack: 
2      OverlayPortalController.hide (package:flutter/src/widgets/overlay.dart:1550:14)
3      _MultiDropdownState._controllerListener (package:multi_dropdown/src/multi_dropdown.dart:321:25)
4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:433:24)
5      MultiSelectController.setItems (package:multi_dropdown/src/controllers/multiselect_controller.dart:45:5)
6      _MultiDropdownState._initializeController (package:multi_dropdown/src/multi_dropdown.dart:260:9)
7      _MultiDropdownState.initState (package:multi_dropdown/src/multi_dropdown.dart:247:5)
8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5618:55)
9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5463:5)
...     Normal element mounting (52 frames)
61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4340:16)
62     Element.updateChild (package:flutter/src/widgets/framework.dart:3849:18)
63     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:860:37)
64     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:845:20)
65     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2845:19)
66     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:837:12)
67     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:360:23)
68     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2688:59)
69     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1097:15)
70     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2688:14)
71     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:5)
72     RenderSliverMultiBoxAdaptor.insertAndLayoutLeadingChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:467:5)
73     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:126:29)
74     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
75     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:121:12)
76     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:327:11)
77     RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
78     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:601:13)
79     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1516:12)
80     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1427:20)
81     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2416:7)
82     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1051:18)
83     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1064:15)
84     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:577:23)
85     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1138:13)
86     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
87     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
88     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
89     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
90     _invoke (dart:ui/hooks.dart:312:13)
91     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
92     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)
The MultiSelectController<ServiceUser> sending notification was: MultiSelectController(options: [], open: false)
====================================================================================================`

**Comment by ARASHz4** [comment]
in multi_dropdown 3.0.1 dropdown items don't disappeared, but selected doesn't come back!

**Comment by oi-narendra** [comment]
@ARASHz4 If you can show me your use case with a replicable code, that will help me further debug. I checked it with the listview and it was working last time. May be I missed your use case.

**Comment by ARASHz4** [comment]
@oi-narendra This is my code

```
import 'package:flutter/material.dart';
import 'package:multi_dropdown/multi_dropdown.dart';

class MultiDropdownTest extends StatefulWidget {
  const MultiDropdownTest({super.key});

  @override
  State<MultiDropdownTest> createState() => _MultiDropdownTestState();
}

class _MultiDropdownTestState extends State<MultiDropdownTest> {

  final namesDropDownController = MultiSelectController<String>();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("MultiDropdown"),
      ),
      body: ListView(
        children: [
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: MultiDropdown<String>.future(
              controller: namesDropDownController,
              future: getNames,
              singleSelect: true,
              searchEnabled: true,
              closeOnBackButton: true,
              fieldDecoration: FieldDecoration(
                labelText: "Names",
                backgroundColor: Colors.transparent,
                border: OutlineInputBorder(
                  borderSide: BorderSide(color: Theme.of(context).dividerColor),
                ),
                suffixIcon: const Icon(Icons.expand_more),
                showClearIcon: false,
              ),
              dropdownDecoration: DropdownDecoration(
                backgroundColor: Theme.of(context).canvasColor,
                borderRadius: const BorderRadius.only(
                  bottomLeft: Radius.circular(8),
                  bottomRight: Radius.circular(8),
                ),
                elevation: 16,
              ),
              dropdownItemDecoration: DropdownItemDecoration(
                backgroundColor: Theme.of(context).canvasColor,
                selectedBackgroundColor: Colors.transparent,
                selectedIcon: Icon(
                  Icons.check_circle,
                  color: Theme.of(context).colorScheme.primary,
                ),
              ),
              chipDecoration: ChipDecoration(
                backgroundColor: Theme.of(context).colorScheme.primary,
              ),
              searchDecoration: const SearchFieldDecoration(
                hintText: "search",
              ),
            ),
          ),
          Container(
            color: Colors.red,
            height: 600,
          ),
          Container(
            color: Colors.green,
            height: 600,
          ),
          Container(
            color: Colors.blue,
            height: 600,
          ),
        ],
      ),
    );
  }

  Future<List<DropdownItem<String>>> getNames() async {
    await Future.delayed(const Duration(milliseconds: 500));

    return [
      DropdownItem(label: "Arash", value: "arash"),
      DropdownItem(label: "Arash2", value: "arash2"),
      DropdownItem(label: "Arash3", value: "arash3"),
    ];
  }
}
```
I used MultiDropdown.future
