### ISSUE TITLE
Initialize selected items onInit (setSelectedOptions)

### ISSUE THREAD

**Issue by mrizkynurfajrie** [oi-narendra/multiselect-dropdown#121]
Hi,
Congratulations for your excellent works after release new stable version of this package a few days ago.

I little bit confused with this update. Before this update (on 2.1.4 ver.) to initiate selected items/options we can use .setSelectedOptions on controller. But in this update i can't see that function anymore. I can't find migration documentation for this feature/function.
Is it replaced with new parameter just like setOptions to setItems, or you just remove it?

**Comment by zhiyuanFan** [comment]
you can init your items with `selected` attribute,  like `DropdownItem(label: value:  selected:true)`

**Comment by mrizkynurfajrie** [comment]
> you can init your items with `selected` attribute, like `DropdownItem(label: value: selected:true)`

Oh okay, i got it.
Thank you mate

**Comment by zhiyuanFan** [comment]
您的来信已收到，我会尽快回复您，谢谢！
