### ISSUE TITLE
Set multi selected item always showing empty selected options

### ISSUE THREAD

**Issue by ferysyukur** [oi-narendra/multiselect-dropdown#138]
Hi @oi-narendra,

Thank you for your great plugin!

I primarily use the multi-select dropdown, but it seems to be not working correctly right now.

Previously, I used the following:
`
selectionType: SelectionType.multi,
selectedOptions: [item1, item2]
`

now, we used controller to set it:

`
for (var option in options) {
  multiDropDownController.selecWhere((element) => element.value.id == option.id)
}
`

However, when I check the dropdown, it always shows empty selections. I’m not sure if this is the correct approach. Could you please clarify this or update the documentation to make it clearer? Thank you in advance!

**Comment by zhiyuanFan** [comment]
https://github.com/oi-narendra/multiselect-dropdown/issues/121#issue-2457073712
this may help you.

**Comment by ferysyukur** [comment]
Thank you @zhiyuanFan.
