### ISSUE TITLE
Dropdown height when no remaining space on screen

### ISSUE THREAD

**Issue by giaur500** [oi-narendra/multiselect-dropdown#18]
Dropdown height should be detected automatically and it should be based on items count and available space left on screen. Fixed dropdown height causes it will be either too low (unnecesary scroll required to show items) or too high (there's no space to display all items and some items will be not possible to select, especially when control is placed at the bottom of window).

Best bahaviour is like built in Flutter DropdownButton has. This issue makes your widget useless in most scenarios.

**Comment by giaur500** [comment]
When no dropdown height is not provided, dropdown height should be:
- shrinked to show all items without blank space
- if there's no room to show all items, dropdown should be auto expanded to fit all available room on screen - below or above, in place where there's more room. Also, no matter what popup height is provided, it should never be cut off, even if provided height is greater than available room on screen.

**Comment by divan** [comment]
> shrinked to show all items without blank space

No updates on this?

**Comment by giaur500** [comment]
I don't know, did you try with merged commits related to this?

**Comment by divan** [comment]
> I don't know, did you try with merged commits related to this?

They supposed to be in pub.dev version, right?
