### ISSUE TITLE
Reset with reset button

### ISSUE THREAD

**Issue by breeze90** [oi-narendra/multiselect-dropdown#24]
Hey!

Thx for the widget!

How can I reset selection?

With regular textfield you could make TextController.clear(), but here its more complicated, is there any solution to change its state to no selections at all without manually removing all the options?

<img width="1503" alt="Screenshot 2023-02-22 at 15 18 37" src="https://user-images.githubusercontent.com/4200640/220617763-156e0673-a6f4-497e-88b9-f0c3a164ef52.png">

void resetFilter() {
  resetFilterBool.value = true;
  searchController.clear();
  notesController.clear();
  resetFilterBool.value = false;
}

I have 4 fields. 2 are textfields. 2 are multidropdowns. I press the button which activates this function. I reset both textfields and filter works correctly. 

Is there any easy solution I can reset 2 other dropdown to none selections? Something like ClearSelection or default view?

**Comment by oi-narendra** [comment]
Well for now you can pass a showClearIcon = true, which will show a clear icon at the end of the dropdown field instead of the dropdown icon if any items are selected.
Clicking on the clear icon clears the selected items.

I am not sure if that fits your use case though.

**Comment by breeze90** [comment]
So far the showClearIcon does not look to work for me, I do not see any difference.  
<img width="1727" alt="Screenshot 2023-02-23 at 10 56 30" src="https://user-images.githubusercontent.com/4200640/220850389-ac8cfd5b-c37d-4cc6-9410-d4ab8723e29b.png">
<img width="429" alt="Screenshot 2023-02-23 at 10 57 05" src="https://user-images.githubusercontent.com/4200640/220850496-5b4bfe8c-69c5-4867-869c-49641ff1eee5.png">
<img width="219" alt="Screenshot 2023-02-23 at 10 57 23" src="https://user-images.githubusercontent.com/4200640/220850535-c98ebc8d-40ed-421a-8163-3ada43a021bd.png">

Well if I manage to get this icon, then i still do not actually understand how I can programmatically clear the selections, is there a way to activate this icon without clicking it?

**Comment by breeze90** [comment]
Could you clarify where I should look for showclearIcon?

**Comment by oi-narendra** [comment]
okay the show clear Icon 
is default to true in the dropdown. 
It will show you a clear icon like this.

<img width="373" alt="Screenshot 2023-02-26 at 17 41 38" src="https://user-images.githubusercontent.com/17561434/221409040-67327b3e-171b-409c-a469-488d4ed2326d.png">

**Comment by oi-narendra** [comment]
I will add a feature to add a controller to the dropdown with the ability to clear, toggle the dropdown, select items, and many more in the next release.

**Comment by breeze90** [comment]
Great news. Are we talking few month?

**Comment by oi-narendra** [comment]
within a month...

**Comment by breeze90** [comment]
Great to hear, this widget is great, deff gonna use int.

**Comment by oi-narendra** [comment]
you can test the prerelease that supports the controller.
https://pub.dev/packages/multi_dropdown/versions/2.0.0-dev.1

**Comment by breeze90** [comment]
Thank you man, this is the game changer for me.
