### ISSUE TITLE
Old http version

### ISSUE THREAD

**Issue by yahyaMajdAlamaal** [oi-narendra/multiselect-dropdown#27]
Hi,
I got this error
`multi_dropdown >=2.0.0 depends on http ^0.13.6 and my_app depends on http ^1.0.0`

Can you please upgrade your http version

**Comment by oi-narendra** [comment]
As per http changelog  [https://pub.dev/packages/http/changelog](url)
```Requires Dart 3.0 or later```

so upgrading to v **_^1.0.0_** would break other projects.

So I will release a beta version for http v ^1.0.0 support, do check it out.
