### ISSUE TITLE
Allow the user to search the options

### ISSUE THREAD

**Issue by Macacoazul01** [oi-narendra/multiselect-dropdown#31]
The suggestion is to add a parameter to allow the user to search the list of avaliable options.

thought of two options of doing this:

1-changing the container that holds the list of selected options to show a text field instead of the options when the overlay is on the screen

2-Adding a search field before the list of options

**Comment by Lorenzobettega** [comment]
there are some widgets that already reproduce this type of behavior like if this can help you:
https://pub.dev/packages/multiple_search_selection
https://pub.dev/packages/easy_search_bar

**Comment by Lorenzobettega** [comment]
To achieve this, you can utilize a Material 3 Widget named SearchBar, which will provide a TextEditingController to help you sort the ListView.builder. Here's a good example
![image](https://github.com/oi-narendra/multiselect-dropdown/assets/84482292/e01cb063-4378-4f25-a68e-00afbf22f20b)

**Comment by oi-narendra** [comment]
Thanks, @Lorenzobettega for the suggestions. I am looking into it.

**Comment by Lorenzobettega** [comment]
I make a code that can help you, look it:
[searchdialog.zip](https://github.com/oi-narendra/multiselect-dropdown/files/12163240/searchdialog.zip)
