### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by oi-narendra** [oi-narendra/multiselect-dropdown#32]
1. Long option names styling.
2. Clear Icon styling (size and position).
3. Dropdown arrow style customization.
4. Grey area issue.
![image](https://github.com/oi-narendra/multiselect-dropdown/assets/17561434/ef7ec0ac-156b-4696-ab06-7f68318d6bd5)

**Comment by Tsovinar2000** [comment]
Any news? I am waiting more that a month for this )
