### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by kgdthomas** [oi-narendra/multiselect-dropdown#4]
I just first want to thank you, this widget is amazing. The best of a checkbox and the best of a dropdownlist in one place. Thank you so much for creating it.

I am currently having issues with two things both font related.

1) The Hint Text cannot be customized to take out the space it has before it (about 5 pixels). I am trying to align the words with other widgets.

2) I am confused how to apply a font like GoogleFonts.roboto to the options and hint. I have used the font throughout my app and I was hoping to change the widget font to the same. 

GoogleFonts.roboto(
  fontWeight: FontWeight.w500,
  color: blackColor,
);

My suggestion is => Allow the use of Text() in "hint:" and "options:", this will allow users to customize their font fully by Text(Textstyle()) and so your widget will be able to more focused on functionality and call other widgets for font aesthetics.

**Comment by oi-narendra** [comment]
Thank you for writing the issue. 
You can apply the style to _**hint**_ and _**option**_ by using optionTextStyle and hintStyle parameters, they both accept a **_TextStyle_**. 
Example: `optionTextStyle: const TextStyle(fontSize: 16),
                  hintStyle: const TextStyle(fontSize: 16),`

For the spacing of the hint, I will update it on the next release.
