### ISSUE TITLE
A MultiSelectController was used after being disposed

### ISSUE THREAD

**Issue by Podrosboy** [oi-narendra/multiselect-dropdown#40]
What to do if this error occurs:
Unhandled Exception: A MultiSelectController was used after being disposed. Once you have called dispose() on a MultiSelectController, it can no longer be used.

I declare and initialize the variable in a separate file:
MultiSelectController controllerFuelType = MultiSelectController();

In the main file I call the widget and this controller
![image](https://github.com/oi-narendra/multiselect-dropdown/assets/124129053/95db2363-1f63-4877-956a-3af36d00263e)

I switch to another tab in the TabBar class and when I return to the tab where the MultiSelectController and the MultiSelectDropDown widget are used, an exception occurs

**Comment by oi-narendra** [comment]
Can you please edit your issue to include the usecase of controller.

**Comment by Podrosboy** [comment]
> Can you please edit your issue to include the usecase of controller.

I have added an example of the error

**Comment by darknight1604** [comment]
I have same issue

**Comment by oi-narendra** [comment]
I am working on fixing this issue. It will be fixed by this weekend.
