### ISSUE TITLE
Example from this readme does not work - is this a mistake?

### ISSUE THREAD

**Issue by Krzysztof-Lempicki** [oi-narendra/multiselect-dropdown#41]
Hi,

#INTRO 

Example code from readme of this repo does not work.
It has < int > type definition that is not supported by code.

Version from: https://pub.dev/packages/multi_dropdown works correctly.

#QUESTION

Which one is newer? 
Is version from repo just a mistake or may it shows improvement that will be later
present on pub.dev ?

**Comment by oi-narendra** [comment]
Yeah, the GitHub Repo version is newer which is yet to be released in pub.dev.
