### ISSUE TITLE
when search enabled= true and then click in search field menu remaining appear and can't  hide why?

### ISSUE THREAD

**Issue by abdo-ahmed-id** [oi-narendra/multiselect-dropdown#46]
MultiSelectDropDown<int>(
        onOptionSelected: (List<ValueItem> selectedOptions) { },
        searchEnabled: true,
        hint: context.loc.enterPropertyLocation,
        selectionType: SelectionType.multi,
        chipConfig: const ChipConfig(
            wrapType: WrapType.wrap,
            backgroundColor: Colors.white,
            deleteIconColor: Colors.red,
            padding: EdgeInsets.zero,
            labelColor: AppColors.primary,
            labelPadding: EdgeInsets.symmetric(horizontal: 8, vertical: 0)),
        dropdownHeight: 500,
        optionTextStyle: AppStyles.bodyMedium,
        selectedOptionIcon: const Icon(Icons.check_circle),
        options: widget.items
                .map((e) => ValueItem(
                      value: e.id,
                      label: e.value ?? '',
                    ))
                .toList() ??
            [],
      ),
      
      
      pupspic.ymal
multi_dropdown: ^2.1.1

**Comment by oi-narendra** [comment]
Can you please explain more clearly or comment some images/videos of the problem?

**Comment by abdo-ahmed-id** [comment]
https://github.com/oi-narendra/multiselect-dropdown/assets/69322263/9f174133-5552-4677-af0d-1152476eba86

**Comment by RafaeldeGomesMonteiro** [comment]
I'm using version `2.1.3` and have the same exact issue.
