### ISSUE TITLE
fail onOptionSelected

### ISSUE THREAD

**Issue by yuyaohongzheng** [oi-narendra/multiselect-dropdown#5]
Function(List<ValueItem>)? onOptionSelected , It didn't work

**Comment by oi-narendra** [comment]
Thank you for the feedback, will fix this asap.

**Comment by Sureya** [comment]
@oi-narendra : this is not fully fixed yet, `onOptionSelected` is only being triggered when adding values to the list. The function is not being triggered while removing items from the list.
