### ISSUE TITLE
Error: A MultiSelectController was used after being disposed.

### ISSUE THREAD

**Issue by Hacheur-1182** [oi-narendra/multiselect-dropdown#51]
<img width="1380" alt="Capture d’écran 2023-12-18 à 20 35 09" src="https://github.com/oi-narendra/multiselect-dropdown/assets/58509219/434ca01a-c3fb-4a84-9b1d-03f13e445baf">

when I send my form this error appears in the console.

**### my code here:**

// import 'dart:ffi';

import 'package:fja_admin/Presentation/widgets/custom_text.dart';
import 'package:fja_admin/controllers/notification_controller.dart';
import 'package:fja_admin/models/section_locale_model.dart';

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:multi_dropdown/multiselect_dropdown.dart';

import '../../../resources/color_manager.dart';
import '../../../resources/value_manager.dart';

class NotificationPage extends StatefulWidget {
  const NotificationPage({super.key});

  @override
  State<NotificationPage> createState() => _NotificationPageState();
}

class _NotificationPageState extends State<NotificationPage> {
  Color primary = ColorManager.primary;
  final _formKey = GlobalKey<FormState>();
  final MultiSelectController _controllerDropdown = MultiSelectController();

  // final controller = Get.put(NotificationController());
  @override
  Widget build(BuildContext context) {
    return GetBuilder(
      init: NotificationController(),
      builder: (controller) {
        return Obx(() => controller.loading.value
            ? const Scaffold(
                body: Center(
                  child: CircularProgressIndicator(),
                ),
              )
            : SingleChildScrollView(
                child: Stack(
                  children: [
                    Center(
                      child: SizedBox(
                        width: MediaQuery.of(context).size.width * .5,
                        child: Form(
                          key: _formKey,
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Container(
                                padding: const EdgeInsets.only(
                                    left: AppPadding.p28,
                                    right: AppPadding.p28,
                                    top: AppPadding.p50,
                                    bottom: AppPadding.p28),
                                child: const CustomText(
                                  text: "Notification générale",
                                ),
                              ),
                              const SizedBox(
                                height: AppSize.s28,
                              ),
                              TextFormField(
                                controller: controller.titleController.value,
                                onChanged: (value) {},
                                style: const TextStyle(
                                  fontSize: 16,
                                  color: Colors.black,
                                ),
                                decoration: InputDecoration(
                                  labelText: "Titre",
                                  enabledBorder: OutlineInputBorder(
                                    borderSide: BorderSide(
                                      color: ColorManager.primary,
                                      width: 2,
                                    ),
                                  ),
                                  focusedBorder: const OutlineInputBorder(
                                    borderSide: BorderSide(
                                      color: Colors.white54,
                                      width: 2,
                                    ),
                                  ),
                                  hintText: "Titre",
                                  hintStyle: const TextStyle(
                                    color: Colors.grey,
                                  ),
                                ),
                              ),
                              const SizedBox(
                                height: 10,
                              ),
                              MultiSelectDropDown(
                                showClearIcon: true,
                                hint: "Select Sections",
                                hintColor: Colors.grey,
                                hintStyle: const TextStyle(
                                  color: Colors.grey,
                                ),
                                borderColor: ColorManager.primary,
                                borderWidth: 2,
                                borderRadius: 4,
                                controller: _controllerDropdown,
                                onOptionSelected: (options) {
                                  if (options.isNotEmpty) {
                                    final groups = controller.selectedGroups;
                                    // debugPrint("options.toString()");
                                    groups.value =
                                        options.map((e) => e.value).toList();
                                    // print("groups");
                                    // print(groups);
                                  }
                                },
                                options: controller.groupOfValueItem,
                                selectionType: SelectionType.multi,
                                chipConfig: const ChipConfig(
                                  wrapType: WrapType.wrap,
                                ),
                                dropdownHeight: 300,
                                optionTextStyle: const TextStyle(fontSize: 16),
                                selectedOptionIcon:
                                    const Icon(Icons.check_circle),
                              ),
                              const SizedBox(
                                height: 10,
                              ),
                              TextFormField(
                                controller: controller.messageController.value,
                                onChanged: (value) {},
                                maxLines: 5,
                                style: const TextStyle(
                                  fontSize: 16,
                                  color: Colors.black,
                                ),
                                decoration: InputDecoration(
                                  labelText: "Message",
                                  enabledBorder: OutlineInputBorder(
                                    borderSide: BorderSide(
                                      color: ColorManager.primary,
                                      width: 2,
                                    ),
                                  ),
                                  focusedBorder: const OutlineInputBorder(
                                    borderSide: BorderSide(
                                      color: Colors.white54,
                                      width: 2,
                                    ),
                                  ),
                                  hintText: "Message",
                                  hintStyle: const TextStyle(
                                    color: Colors.grey,
                                  ),
                                ),
                              ),
                              const SizedBox(
                                height: AppSize.s20,
                              ),
                              Obx(
                                () => InkWell(
                                  onTap: () {
                                    controller.sendNotifWithApi();
                                  },
                                  child: controller.loading.value
                                      ? const Center(
                                          child: CircularProgressIndicator(),
                                        )
                                      : Container(
                                          height: 45,
                                          color: Colors.green,
                                          child: const Center(
                                            child: Text("Envoyer"),
                                          ),
                                        ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ));
      },
    );
  }
}

**Comment by omkarlhr9595** [comment]
when we can expect to get the solution for this bug

**Comment by oi-narendra** [comment]
@omkarlhr9595 Can you please share your usage code where you are experiencing this bug?
I am trying to replicate issue.

**Comment by omkarlhr9595** [comment]
Its occurring when we navigate back end forth between screens

**Comment by omkarlhr9595** [comment]
@oi-narendra  Do we need to pass Generic to controller
`final MultiSelectController<User> _controller = MultiSelectController();`
like above example

**Comment by oi-narendra** [comment]
Yes, it is recommended.

**Comment by omkarlhr9595** [comment]
I am not giving it
I think thats the reason
Can you please give me instructions to write that class

**Comment by omkarlhr9595** [comment]
```
The type 'MultiSelectController' is declared with 0 type parameters, but 1 type arguments were given.
Try adjusting the number of type arguments to match the number of type parameters. 
```

**Comment by oi-narendra** [comment]
Can you show me usage code?

**Comment by omkarlhr9595** [comment]
`final MultiSelectController<User>  _controller = MultiSelectController();`

**Comment by oi-narendra** [comment]
Did you also pass the model to the dropdown
`MultiSelectDropDown<User>(controller: _controller,`

**Comment by omkarlhr9595** [comment]
no

**Comment by omkarlhr9595** [comment]
<img width="512" alt="Screenshot 2024-01-04 at 7 26 45 PM" src="https://github.com/oi-narendra/multiselect-dropdown/assets/65306391/56c9b6f9-52d1-4686-8057-1138aa37bf4a">

**Comment by oi-narendra** [comment]
Hi, Are you available for a conference call?
If you are please join here so that I can have a look.
https://meet.google.com/dfg-yxib-axa

**Comment by omkarlhr9595** [comment]
Thank for your for your help but I can't join the call
I will try my best to solve this issue by looking at example file
Keep doing great work like this, Thank you so much
