### ISSUE TITLE
onOptionSelected and onOptionRemoved are triggered at the same time

### ISSUE THREAD

**Issue by zam101** [oi-narendra/multiselect-dropdown#62]
when an item/option is removed from the list the onOptionSelected is also triggered  this can cause issues , for example in my case when a user select an option i am calling an api to add the item in db and when he remove an option i am calling another api to delete the item from db and since they are  both triggered at the same time two api calls are sent to the backend ... also it would be better if onOptionSelected function had only the one selected option as a parameter instead of a list of all selected options .

**Comment by oi-narendra** [comment]
Migrate to the latest version [v3.0.0](https://pub.dev/packages/multi_dropdown)
