### ISSUE TITLE
Preselected and disabled chips throw exception when trying to remove them [Improvement]

### ISSUE THREAD

**Issue by Eliathoran** [oi-narendra/multiselect-dropdown#65]
Case:
- Pre-selected fields that can't be removed (disabled).
- They should also be disabled as chips (have a disabled color? and not have the x button).

Current behavior:
- Pre-selected fields disabled can't be removed.
- They are not shown differently in the UI.
- The X button is clickable.
- Throws exception when clicked.

**Comment by Eliathoran** [comment]
Hi there, I have done an implementation for this issue.

I could create a pull request so you can take a look into it :)

**Comment by Eliathoran** [comment]
![image](https://github.com/oi-narendra/multiselect-dropdown/assets/9608948/ad83c5e7-16f4-4e83-a3fc-327e3862aced)

**Comment by oi-narendra** [comment]
Sure. Please create one.

**Comment by Eliathoran** [comment]
Great! I can have access to push a new brach so I can create the PR? 

Thanks in advance! :D

**Comment by oi-narendra** [comment]
You should create PR by forking.
Fork the branch.
Clone it, make changes, commit and push.
Then create PR from your forked repo.

**Comment by Eliathoran** [comment]
https://github.com/oi-narendra/multiselect-dropdown/pull/67
