### ISSUE TITLE
Usage within a Form

### ISSUE THREAD

**Issue by darkfrog26** [oi-narendra/multiselect-dropdown#70]
I'm trying to use this widget within a form where every other field has `InputDecoration` to set the `labelText`. Is there any way to do something like this with this widget so it renders consistently?

**Comment by darkomenx** [comment]
@darkfrog26 Can you go up your data widget multi_select into your main Form widget for validation ? I try to use this widget into a form but nothing data appear into my form object when I doing this :  `formKey.currentState!.value`

**Comment by oi-narendra** [comment]
Check [Beta](https://pub.dev/packages/multi_dropdown/versions/3.0.0-beta.1) version.

**Comment by oi-narendra** [comment]
Migrate to the latest version [v3.0.0](https://pub.dev/packages/multi_dropdown)
