### ISSUE TITLE
Remove or set chip border

### ISSUE THREAD

**Issue by SabrosaStrawberry** [oi-narendra/multiselect-dropdown#71]
Chips are rendering with a border outline, could this be updated with an input parameter?

**Comment by SabrosaStrawberry** [comment]
![image](https://github.com/oi-narendra/multiselect-dropdown/assets/37934643/534ff93d-be2a-4e48-899b-a713199899ff)

**Comment by Eliathoran** [comment]
https://github.com/oi-narendra/multiselect-dropdown/pull/67
