### ISSUE TITLE
need override ValueItem  operator == 

### ISSUE THREAD

**Issue by yuyaohongzheng** [oi-narendra/multiselect-dropdown#8]
for contains :
    **itemBuilder: (context, index) {
                            final option = options[index];
                            final isSelected = selectedOptions.contains(option);**

 need overrid equal
class ValueItem {
   @override
  bool operator == (Object other) {
    if (identical(this, other)) {
      return true;
    }
    return other is ValueItem  && value == other.value;
  }

  @override
  int get hashCode {
    return value.hashCode;
  }

**Comment by oi-narendra** [comment]
already added.
