### ISSUE TITLE
Changing options won't update UI.

### ISSUE THREAD

**Issue by Jara92** [oi-narendra/multiselect-dropdown#81]
I have MultiSelectDropDown inside BlocBuilder. It looks like this:

```dart
MultiSelectDropDown(
      controller: _controller,
      dropdownHeight: 200,
      onOptionSelected: (options) {},
      options: state.options,
    )
```

When I update state.options inside my Bloc, the UI remains the same - initial options are displayed. But this button put after the multi select works: 

```dart
OutlinedButton(
     onPressed: (){
          _controller.setOptions(state.options);
     },
     child: Text("Dummy"))
```

Calling `_controller.setOptions(state.options);` inside BlocListener doesn't work either.

The problem occurs only in the newest version 2.1.4. Version 2.1.3 works fine for me.

**Comment by Danyx1980** [comment]
I'm having the same issue, even calling `widget.controller.clearSelection(option);` inside `onOptionRemoved` doesn't update the UI, but does update the `selectedOptions` list.

**Comment by Istiak-Ahmed78** [comment]
I'm facing the same issue. 😞

**Comment by JeromeTseng** [comment]
Dude,I got the same question,but i have an idea.  I use **UniqueKey**  to force update, and it works.
![image](https://github.com/oi-narendra/multiselect-dropdown/assets/101850164/a2e87565-a36d-4612-a1cb-e6761e0bdcd0)
![image](https://github.com/oi-narendra/multiselect-dropdown/assets/101850164/a37c7302-6f70-41e9-a604-a9a984b7f89c)

**Comment by mvitoriapereirac** [comment]
> Dude,I got the same question,but i have an idea. I use **UniqueKey** to force update, and it works.
> ![image](https://private-user-images.githubusercontent.com/101850164/325815750-a2e87565-a36d-4612-a1cb-e6761e0bdcd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODI5MzcsIm5iZiI6MTcxNDQ4MjYzNywicGF0aCI6Ii8xMDE4NTAxNjQvMzI1ODE1NzUwLWEyZTg3NTY1LWEzNmQtNDYxMi1hMWNiLWU2NzYxZTBiZGNkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxMzEwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2MyMDFmNGY3NGQyNTY3OTBhZGVjMjU1MjE3MDM5MGE5NDk0MTdkNDlkOTA0YjgzYjE3ODg4OWRlNTRjODJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BiPYqYAw6Hla4l42ffzZJjjPH4hd5KdrZ040yH0vMaM)
> ![image](https://private-user-images.githubusercontent.com/101850164/325815818-a37c7302-6f70-41e9-a604-a9a984b7f89c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODI5MzcsIm5iZiI6MTcxNDQ4MjYzNywicGF0aCI6Ii8xMDE4NTAxNjQvMzI1ODE1ODE4LWEzN2M3MzAyLTZmNzAtNDFlOS1hNjA0LWE5YTk4NGI3Zjg5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxMzEwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWJmYmU4ODJmMGFkMmIxYmZlODc0OTEwZGE2ZDVhOTAzZGYyYWEwOTBjODExNmFiYjMzMzRkNWRmZDgyNjlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TA4AGkSDND9pojrbtGAeXbzkZLcRx4ZEPdXw81UUBrw)

That was really helpful! Thanks. Could you explain a bit further why does it work?

**Comment by JeromeTseng** [comment]
> > Dude,I got the same question,but i have an idea. I use **UniqueKey** to force update, and it works.
> > ![image](https://private-user-images.githubusercontent.com/101850164/325815750-a2e87565-a36d-4612-a1cb-e6761e0bdcd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODI5MzcsIm5iZiI6MTcxNDQ4MjYzNywicGF0aCI6Ii8xMDE4NTAxNjQvMzI1ODE1NzUwLWEyZTg3NTY1LWEzNmQtNDYxMi1hMWNiLWU2NzYxZTBiZGNkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxMzEwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2MyMDFmNGY3NGQyNTY3OTBhZGVjMjU1MjE3MDM5MGE5NDk0MTdkNDlkOTA0YjgzYjE3ODg4OWRlNTRjODJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BiPYqYAw6Hla4l42ffzZJjjPH4hd5KdrZ040yH0vMaM)
> > ![image](https://private-user-images.githubusercontent.com/101850164/325815818-a37c7302-6f70-41e9-a604-a9a984b7f89c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODI5MzcsIm5iZiI6MTcxNDQ4MjYzNywicGF0aCI6Ii8xMDE4NTAxNjQvMzI1ODE1ODE4LWEzN2M3MzAyLTZmNzAtNDFlOS1hNjA0LWE5YTk4NGI3Zjg5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQxMzEwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWJmYmU4ODJmMGFkMmIxYmZlODc0OTEwZGE2ZDVhOTAzZGYyYWEwOTBjODExNmFiYjMzMzRkNWRmZDgyNjlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TA4AGkSDND9pojrbtGAeXbzkZLcRx4ZEPdXw81UUBrw)
> 
> That was really helpful! Thanks. Could you explain a bit further why does it work?

I'm sorry to reply to you so late, this involves a UI reuse problem, we updated some options in the dropdown, expecting it to take effect and update the UI, but flutter didn't do this and reused the last UI, if you use **UniqueKey**, it signifies, every UI rendering has to be redrawn, so your new options will take effect and render on the screen, I don't know if I understand it right

**Comment by oi-narendra** [comment]
Migrate to the latest version [v3.0.0](https://pub.dev/packages/multi_dropdown)
