### ISSUE TITLE
Search parameter on ^2.0.0 ver.

### ISSUE THREAD

**Issue by mrizkynurfajrie** [oi-narendra/multiselect-dropdown#86]
Hi there,
I really appreciate about this package, this is a greatful & useful package.

I have a question, can i use search parameter on ^2.0.0 version? I have to use that version because several package in my project depend on http ^0.13.0, and this package only support http^0.13.0 on ^2.0.0 version.

Thank you

**Comment by oi-narendra** [comment]
[v3.0.0](https://pub.dev/packages/multi_dropdown) now supports this. Please migrate to the latest version. This version does not use HTTP package anymore.
