### ISSUE TITLE
hintFontSize change option size rather than hint size

### ISSUE THREAD

**Issue by Masadow** [oi-narendra/multiselect-dropdown#90]
Changing hintFontSize modifies the font size of the options rather than the hint.

hintColor and hintStyle works as expected so one can use hintStyle as a workaround

**Comment by oi-narendra** [comment]
Check [Beta](https://pub.dev/packages/multi_dropdown/versions/3.0.0-beta.1) version.

**Comment by oi-narendra** [comment]
Migrate to the latest version [v3.0.0](https://pub.dev/packages/multi_dropdown).
