### ISSUE TITLE
Cannot select options that are not in the options list

### ISSUE THREAD

**Issue by KaranChoudhary8** [oi-narendra/multiselect-dropdown#92]
Showing this exeption dispite using correct selected options list...
my setOption list = [ValueItem(label: Heart, value: 1714993671734), ValueItem(label: Brain, value: 1714993694203), ValueItem(label: Children, value: 1714993738424)]
my setSelectedOption list = [ValueItem(label: Heart, value: 1714993671734), ValueItem(label: Brain, value: 1714993694203), ValueItem(label: Children, value: 1714993738424)]

**Comment by oi-narendra** [comment]
Migrate to the latest version [v3.0.0](https://pub.dev/packages/multi_dropdown).
