### ISSUE TITLE
[3.0.0-dev.1] onSelectionChanged does not fire when deselecting an item or clearing all items

### ISSUE THREAD

**Issue by amkuchta** [oi-narendra/multiselect-dropdown#95]
As the title states, `onSelectionChanged` does not fire when items are deselected or when all items are cleared; it's not until a new item is selected that `onSelectionChanged` returns an updated list.

**Comment by oi-narendra** [comment]
https://pub.dev/packages/multi_dropdown/versions/3.0.0-dev.2

**Comment by BenCherif** [comment]
[3.0.0-dev.2](https://pub.dev/packages/multi_dropdown/versions/3.0.0-dev.2)
not support on the web

**Comment by oi-narendra** [comment]
Migrate to the latest version [v3.0.0](https://pub.dev/packages/multi_dropdown).
