### ISSUE TITLE
Drop down selection issue

### ISSUE THREAD

**Issue by SatyaMirthipati** [oi-narendra/multiselect-dropdown#96]
Can please add a button for the dropdown list, when the drop-down is open scroll is not working on the screen. 
A button is needed for selecting options like submit for users to experience as well because it is confusing for users after they select the options they have to tap outside which is not aware by everyone to do action except the developers.

**Comment by oi-narendra** [comment]
Check [Beta](https://pub.dev/packages/multi_dropdown/versions/3.0.0-beta.1) version.
You can pass a `header` or `footer` widget to the dropdown and use the controller to dismiss the dropdown.

**Comment by oi-narendra** [comment]
Migrate to the latest version [v3.0.0](https://pub.dev/packages/multi_dropdown).

**Comment by SatyaMirthipati** [comment]
Thank you
