### ISSUE TITLE
Duplicate items in multidropdown

### ISSUE THREAD

**Issue by BenCherif** [oi-narendra/multiselect-dropdown#98]
Hi thanks for awesome package , i've faced an issue which is   the items if  it's not selected on the list it shows duplicate items on chips tags.

<img width="697" alt="Screenshot 2024-05-24 at 11 54 56" src="https://github.com/oi-narendra/multiselect-dropdown/assets/12634281/b19054a7-7af4-4457-b964-e9ed675ca698">

**Comment by oi-narendra** [comment]
Migrate to the latest version [v3.0.0](https://pub.dev/packages/multi_dropdown).
